import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// Generated by global-setup.js at test-run time — never committed (synthetic
// audio only, no real recordings). See TEST_PLAN.md section F.
export const FIXTURES_DIR = path.join(__dirname, '.fixtures')
export const TONE_WAV = path.join(FIXTURES_DIR, 'tone.wav')
export const LONG_TONE_WAV = path.join(FIXTURES_DIR, 'long_tone.wav')
export const JUNK_BIN = path.join(FIXTURES_DIR, 'junk.bin')
